In [17]:
import numpy as np
import os
import pandas as pd
from pathlib import Path
from matplotlib.image import imread
import pickle as plk
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_val_predict
from sklearn.base import clone, BaseEstimator
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, precision_recall_curve, roc_curve, roc_auc_score

In [18]:
dataset_path = Path(os.path.join('c:',os.sep, 'Users', 'Usuario', 'Desktop', 'Facul', 'Aps6_parcial', 'V20220930_partial'))

In [19]:
path_labels = {}

path_labels['a'] = dataset_path.joinpath('a_l/train_61')
path_labels['e'] = dataset_path.joinpath('e_l/train_65')
path_labels['i'] = dataset_path.joinpath('i_l/train_69')
path_labels['o'] = dataset_path.joinpath('o_l/train_6f')
path_labels['u'] = dataset_path.joinpath('u_l/train_75')
path_labels['A'] = dataset_path.joinpath('A_u/train_41')
path_labels['E'] = dataset_path.joinpath('E_u/train_45')
path_labels['I'] = dataset_path.joinpath('I_u/train_49')
path_labels['O'] = dataset_path.joinpath('O_u/train_4f')
path_labels['U'] = dataset_path.joinpath('U_u/train_55')

In [20]:
label_to_file = {
    k: [dataset_path / path_label / file for file in os.listdir(dataset_path / path_label)]  # NOQA:E501
    for k, path_label in path_labels.items()
}

In [21]:
X = []
y = []
for key, files in label_to_file.items():
    for path in files:
        y.append(key)
        image = imread(path)
        binary_matrix = []
        for line in image:
            binary_matrix.append([int(cell[0]) for cell in line])

        X.append(np.array(binary_matrix))

In [23]:
#X = [x.reshape(1, -1) for x in X]

In [24]:
X = np.array(X)

In [25]:
y = np.array(y)

In [26]:
y = ((y=='i')|(y=='I'))

In [27]:
split_test_threshold = 0.2

In [28]:
selection_iter = StratifiedShuffleSplit(n_splits=1, test_size=split_test_threshold, random_state=42)

In [29]:
train_index, test_index = next(selection_iter.split(X, y))

In [30]:
X_train = X[train_index]
X_test = X[test_index]
y_train = y[train_index]
y_test = y[test_index]

Alguns testes:

In [31]:
#y_train

array([ True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False,  True,

In [32]:
#y_test

array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False,  True, False, False,  True,
        True, False, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,

In [33]:
#len(y)

900

In [34]:
#len(y_train)

720

In [35]:
#np.sum(y_train)

144

In [36]:
#np.sum(y_train)/len(y_train)

0.2

In [37]:
#len(y_test)

180

In [38]:
#np.sum(y_test)

36

In [39]:
#np.sum(y_test)/len(y_test)

0.2

In [40]:
#type(train_index)

numpy.ndarray

Para salvar e carregar as váriaveis:

In [41]:
#with open('train_index.npy', 'wb') as f:
#    np.save(f, train_index)

In [42]:
#with open('test_index.npy', 'wb') as f:
#    np.save(f, test_index)

In [43]:
#with open('X.npy', 'wb') as f:
#    np.save(f, X)

In [44]:
#with open('y.npy', 'wb') as f:
#    np.save(f, y)

In [45]:
#with open('X_train.npy', 'wb') as f:
#    np.save(f, X_train)

In [46]:
#with open('X_test.npy', 'wb') as f:
#    np.save(f, X_test)

In [47]:
#with open('y_train.npy', 'wb') as f:
#    np.save(f, y_train)

In [48]:
#with open('y_test.npy', 'wb') as f:
#    np.save(f, y_test)

In [49]:
#with open('train_index.npy', 'rb') as f:
#    train_index = np.load(f)

In [50]:
#with open('test_index.npy', 'rb') as f:
#    test_index = np.load(f)

In [51]:
#with open('X.npy', 'rb') as f:
#    X = np.load(f)

In [52]:
#with open('y.npy', 'rb') as f:
#    y = np.load(f)

In [53]:
#with open('X_train.npy', 'rb') as f:
#    X_train = np.load(f)

In [54]:
#with open('X_test.npy', 'rb') as f:
#    X_test = np.load(f)

In [55]:
#with open('y_train.npy', 'rb') as f:
#    y_train = np.load(f)

In [56]:
#with open('y_test.npy', 'rb') as f:
#    y_test = np.load(f)

In [57]:
y_train_i = (y_train==True)
y_test_i = (y_test==True)

In [58]:
y_train_i[0]

True

Redimensionar para 2 dimensões:

In [59]:
nsamples, nxtrain, nytrain = X_train.shape
d2_X_train = X_train.reshape((nsamples,nxtrain*nytrain))

nsamples, nxtest, nytest = X_test.shape
d2_X_test = X_test.reshape((nsamples,nxtest*nytest))

Classificador SGD

In [61]:
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(d2_X_train, y_train_i)

SGDClassifier(random_state=42)

In [62]:
#y_test[23]

False

In [63]:
#sgd_clf.predict([d2_X_test[23]])

array([False])

In [64]:
def my_cross_val_score(clf, X_train: pd.array, y_train: pd.array):
    skfolds = StratifiedKFold(n_splits=3, random_state=42, shuffle=True)

    for train_index, test_index in skfolds.split(X_train, y_train):
        clone_cfl = clone(clf)
        X_train_folds = X_train[train_index]
        y_train_folds = y_train[train_index]
        X_test_folds = X_train[test_index]
        y_test_folds = y_train[test_index]

        clone_cfl.fit(X_train_folds, y_train_folds)
        y_pred = clone_cfl.predict(X_test_folds)
        n_correct = sum(y_pred == y_test_folds)
        print((n_correct/len(y_pred)))

In [65]:
my_cross_val_score(sgd_clf, d2_X_train, y_train_i)

0.95
0.9541666666666667
0.9666666666666667


In [66]:
cross_val_score(sgd_clf, d2_X_train, y_train_i, cv=3, scoring='accuracy')

array([0.84166667, 0.95833333, 0.9375    ])

In [67]:
y_train_pred = cross_val_predict(sgd_clf, d2_X_train, y_train_i, cv=3)

In [68]:
confusion_matrix(y_train_i, y_train_pred)

array([[525,  51],
       [ 12, 132]], dtype=int64)

In [69]:
precision_score(y_train_i, y_train_pred)

0.7213114754098361

In [70]:
recall_score(y_train_i, y_train_pred)

0.9166666666666666

In [71]:
f1_score(y_train_i, y_train_pred)

0.8073394495412843

Rede Neural:

In [ ]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(100, 50), activation='relu', solver='sgd', random_state=42)
mlp_clf.fit(d2_X_train, y_train_i)

C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(100, 50), random_state=42, solver='sgd')

In [ ]:
#mlp_clf.predict([d2_X_test[0]])

array([False])

In [ ]:
y_train_pred_RN = cross_val_predict(mlp_clf, d2_X_train, y_train_i, cv=2)

C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Usuario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
confusion_matrix(y_train_i, y_train_pred_RN)

array([[568,   8],
       [ 10, 134]], dtype=int64)

In [ ]:
precision_score(y_train_i, y_train_pred_RN)

0.9436619718309859

In [ ]:
recall_score(y_train_i, y_train_pred_RN)

0.9305555555555556

In [ ]:
f1_score(y_train_i, y_train_pred_RN)

0.9370629370629372